output "certificate_authority_arn" {
  description = "The Amazon Resource Name (ARN) of the Certificate Authority."
  value       = aws_acmpca_certificate_authority.this.arn
}

output "certificate" {
  description = "The PEM-encoded Certificate Authority certificate."
  value       = aws_acmpca_certificate.this.certificate
}

output "certificate_chain" {
  description = "The PEM-encoded Certificate Authority certificate chain."
  value       = local.is_root ? null : aws_acmpca_certificate.this.certificate_chain
}

output "certificate_signing_request" {
  description = "The PEM-encoded Certificate Signing Request (CSR) generated by the CA."
  value       = aws_acmpca_certificate_authority.this.certificate_signing_request
}

output "crl_s3_bucket_name" {
  description = "The name of the S3 bucket used to store CRLs."
  value       = local.crl_bucket_name
}

output "crl_s3_bucket_arn" {
  description = "The ARN of the S3 bucket used to store CRLs (if created by this module)."
  value       = local.create_crl_bucket ? aws_s3_bucket.crl[0].arn : null
}

output "ocsp_log_group_arn" {
  description = "The ARN of the CloudWatch Log Group created for OCSP logging."
  value       = var.enable_ocsp && var.create_ocsp_log_group ? aws_cloudwatch_log_group.ocsp[0].arn : null
}
