terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0"
    }
  }
}

# Local variables for common resources configuration
locals {
  # Merged tags block as per requirements.
  # Note: Standard V1 SES resources do not support tags, but this local is ready 
  # for other taggable resources (like future Route53 or S3 features).
  tags = merge({
    Name = var.name
  }, var.tags)
}

# ==========================================
# Domain Verification & Identity
# ==========================================

resource "aws_ses_domain_identity" "this" {
  count  = var.domain != null && var.domain != "" ? 1 : 0
  domain = var.domain
}

resource "aws_ses_domain_dkim" "this" {
  count  = var.domain != null && var.domain != "" ? 1 : 0
  domain = aws_ses_domain_identity.this[0].domain
}

# Route53 TXT record for domain ownership verification
resource "aws_route53_record" "ses_verification" {
  count   = var.domain != null && var.domain != "" && var.zone_id != null ? 1 : 0
  zone_id = var.zone_id
  name    = "_amazonses.${var.domain}"
  type    = "TXT"
  ttl     = "600"
  records = [aws_ses_domain_identity.this[0].verification_token]
}

# Route53 CNAME records for DKIM verification (3 records generated by SES)
resource "aws_route53_record" "ses_dkim" {
  count   = var.domain != null && var.domain != "" && var.zone_id != null ? 3 : 0
  zone_id = var.zone_id
  name    = "${aws_ses_domain_dkim.this[0].dkim_tokens[count.index]}._domainkey.${var.domain}"
  type    = "CNAME"
  ttl     = "600"
  records = ["${aws_ses_domain_dkim.this[0].dkim_tokens[count.index]}.dkim.amazonses.com"]
}

# ==========================================
# Individual Email Verification
# ==========================================

resource "aws_ses_email_identity" "this" {
  for_each = toset(var.emails)
  email    = each.value
}

# ==========================================
# Incoming Email Processing (Receipt Rules)
# ==========================================

# Receipt Rule Set
resource "aws_ses_receipt_rule_set" "this" {
  count         = var.enable_incoming_email ? 1 : 0
  rule_set_name = "${var.name}-receipt-rules"
}

# Receipt Rules
resource "aws_ses_receipt_rule" "this" {
  for_each      = var.enable_incoming_email ? { for rule in var.receipt_rules : rule.name => rule } : {}
  name          = each.value.name
  rule_set_name = aws_ses_receipt_rule_set.this[0].rule_set_name
  recipients    = each.value.recipients
  enabled       = each.value.enabled
  scan_enabled  = each.value.scan_enabled
  tls_policy    = each.value.tls_policy
  after         = each.value.after

  # Add header action
  dynamic "add_header_action" {
    for_each = lookup(each.value, "add_header_actions", [])
    content {
      header_name  = add_header_action.value.header_name
      header_value = add_header_action.value.header_value
      position     = add_header_action.value.position
    }
  }

  # Bounce action
  dynamic "bounce_action" {
    for_each = lookup(each.value, "bounce_actions", [])
    content {
      message         = bounce_action.value.message
      sender          = bounce_action.value.sender
      smtp_reply_code = bounce_action.value.smtp_reply_code
      status_code     = lookup(bounce_action.value, "status_code", null)
      topic_arn       = lookup(bounce_action.value, "topic_arn", null)
      position        = bounce_action.value.position
    }
  }

  # Lambda action
  dynamic "lambda_action" {
    for_each = lookup(each.value, "lambda_actions", [])
    content {
      function_arn    = lambda_action.value.function_arn
      invocation_type = lookup(lambda_action.value, "invocation_type", null)
      topic_arn       = lookup(lambda_action.value, "topic_arn", null)
      position        = lambda_action.value.position
    }
  }

  # S3 action (stores raw emails in bucket)
  dynamic "s3_action" {
    for_each = lookup(each.value, "s3_actions", [])
    content {
      bucket_name       = s3_action.value.bucket_name
      object_key_prefix = lookup(s3_action.value, "object_key_prefix", null)
      topic_arn         = lookup(s3_action.value, "topic_arn", null)
      position          = s3_action.value.position
      kms_key_arn       = lookup(s3_action.value, "kms_key_arn", null)
    }
  }

  # SNS action
  dynamic "sns_action" {
    for_each = lookup(each.value, "sns_actions", [])
    content {
      topic_arn = sns_action.value.topic_arn
      position  = sns_action.value.position
      encoding  = lookup(sns_action.value, "encoding", null)
    }
  }

  # Stop action
  dynamic "stop_action" {
    for_each = lookup(each.value, "stop_actions", [])
    content {
      scope     = stop_action.value.scope
      topic_arn = lookup(stop_action.value, "topic_arn", null)
      position  = stop_action.value.position
    }
  }

  # Workmail action
  dynamic "workmail_action" {
    for_each = lookup(each.value, "workmail_actions", [])
    content {
      organization_arn = workmail_action.value.organization_arn
      topic_arn        = lookup(workmail_action.value, "topic_arn", null)
      position         = workmail_action.value.position
    }
  }
}

# Activate Receipt Rule Set
# Depends on individual rules being created first to avoid empty/partial active rulesets.
resource "aws_ses_active_receipt_rule_set" "this" {
  count         = var.enable_incoming_email ? 1 : 0
  rule_set_name = aws_ses_receipt_rule_set.this[0].rule_set_name

  depends_on = [aws_ses_receipt_rule.this]
}

# ==========================================
# Tracking & Analytics (Configuration Sets)
# ==========================================

resource "aws_ses_configuration_set" "this" {
  count                      = var.enable_configuration_set ? 1 : 0
  name                       = var.name
  reputation_metrics_enabled = var.configuration_set_reputation_metrics_enabled
  sending_enabled            = var.configuration_set_sending_enabled

  # TLS policy settings for deliveries
  dynamic "delivery_options" {
    for_each = var.configuration_set_tls_policy != null ? [1] : []
    content {
      tls_policy = var.configuration_set_tls_policy
    }
  }

  # Custom tracking options for tracking links
  dynamic "tracking_options" {
    for_each = var.configuration_set_custom_redirect_domain != null ? [1] : []
    content {
      custom_redirect_domain = var.configuration_set_custom_redirect_domain
    }
  }
}

# Event Destinations for Configuration Set
resource "aws_ses_event_destination" "this" {
  for_each               = var.enable_configuration_set ? { for ed in var.event_destinations : ed.name => ed } : {}
  name                   = each.value.name
  configuration_set_name = aws_ses_configuration_set.this[0].name
  enabled                = lookup(each.value, "enabled", true)
  matching_types         = each.value.matching_types

  dynamic "sns_destination" {
    for_each = each.value.sns_destination != null ? [each.value.sns_destination] : []
    content {
      topic_arn = sns_destination.value.topic_arn
    }
  }

  dynamic "cloudwatch_destination" {
    for_each = each.value.cloudwatch_destination != null ? [each.value.cloudwatch_destination] : []
    content {
      default_value  = cloudwatch_destination.value.default_value
      dimension_name = cloudwatch_destination.value.dimension_name
      value_source   = cloudwatch_destination.value.value_source
    }
  }

  dynamic "kinesis_destination" {
    for_each = each.value.kinesis_destination != null ? [each.value.kinesis_destination] : []
    content {
      stream_arn = kinesis_destination.value.stream_arn
      role_arn   = kinesis_destination.value.role_arn
    }
  }
}
